db.sales.aggregate([
    {
      $group: {
        _id: "$product",
        totalRevenue: { $sum: { $multiply: ["$price", "$quantity"] } },
        totalQuantitySold: { $sum: "$quantity" },
        avgPricePerUnit: { $avg: "$price" }
      }
    },
    {
      $sort: { totalRevenue: -1 }
    }
  ])
  
  // Average Age and Gender Distribution of a User's Friends
  
  db.users.aggregate([
    {
      $project: {
        _id: 0,
        name: 1,
        avgFriendAge: { $avg: "$friends.age" },
        genderDistribution: {
          $arrayToObject: {
            $map: {
              input: { $zip: { inputs: ["$friends.gender", "$friends"] } },
              as: "friend",
              in: {
                k: { $toString: { $arrayElemAt: ["$$friend", 0] } },
                v: "$$friend.age"
              }
            }
          }
        }
      }
    },
    {
      $sort: { $size: "$friends" }
    }
  ])
  // Average Rating for Each Genre
  
  db.movies.aggregate([
    {
      $unwind: "$ratings"
    },
    {
      $group: {
        _id: "$genre",
        averageRating: { $avg: "$ratings.score" }
      }
    },
    {
      $sort: { averageRating: -1 }
    }
  ])
  // Total Revenue and Number of Orders for Each Customer
  
  db.orders.aggregate([
    {
      $lookup: {
        from: "customers",
        localField: "customer_id",
        foreignField: "customer_id",
        as: "customer"
      }
    },
    {
      $unwind: "$customer"
    },
    {
      $group: {
        _id: "$customer.name",
        totalRevenue: { $sum: { $multiply: ["$price", "$quantity"] } },
        numberOfOrders: { $sum: 1 }
      }
    },
    {
      $sort: { totalRevenue: -1 }
    }
  ])
  
  // Total Amount of Orders Placed by Each Customer for a Given Date Range
  
  db.orders.aggregate([
    {
      $match: {
        order_date: {
          $gte: ISODate("2022-03-01"),
          $lte: ISODate("2022-03-31")
        }
      }
    },
    {
      $group: {
        _id: "$customer_id",
        totalAmount: { $sum: "$total_amount" }
      }
    }
  ])
  // Number of Events of Each Type Triggered by Each User for a Given Date Range
  
  db.events.aggregate([
    {
      $match: {
        event_date: {
          $gte: ISODate("2022-01-01"),
          $lte: ISODate("2022-01-31")
        }
      }
    },
    {
      $group: {
        _id: { user_id: "$user_id", event_type: "$event_type" },
        count: { $sum: 1 }
      }
    }
  ])
  // Total Revenue Generated by Each Product for a Given Date Range
  
  db.sales.aggregate([
    {
      $match: {
        sale_date: {
          $gte: ISODate("2022-01-01"),
          $lte: ISODate("2022-01-31")
        }
      }
    },
    {
      $group: {
        _id: "$product_id",
        totalRevenue: { $sum: { $multiply: ["$price", "$quantity"] } }
      }
    }
  ])